### ISSUE TITLE
sample app module build has missing quotes in plugin import declaration

### ISSUE THREAD

**Issue by shareme** [novoda/gradle-build-properties-plugin#65]
title says it all missing quotes in plugin import

https://github.com/novoda/gradle-build-properties-plugin/blob/master/sample/app/build.gradle

**Comment by tasomaniac** [comment]
Hi, this is working as intended. The sample uses old trick to configure buildSrc to include the plugin. That's why the fully qualified name of the class is required to apply the plugin.

The sample should be migrated to use composite builds instead. That would allow the plugin to be applied in a normal way. 

Just like how it is done here. https://github.com/novoda/gradle-static-analysis-plugin/blob/master/sample/settings.gradle

**Comment by mr-archano** [comment]
@tasomaniac actually: https://github.com/novoda/gradle-build-properties-plugin/pull/64
> Use Gradle composite builds in sample

That PR is not in `master` yet 💃
